// <auto-generated />
using DataLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(InsuranceContext))]
    [Migration("20210121110322_Initial-Database")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayer.Models.DescriptionOfCustomerInsurance", b =>
                {
                    b.Property<int>("DescriptionInsurancesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionInsurances")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndInsurances")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameInsurances")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberInsurances")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousCompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousNumberInsurance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartInsurances")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DescriptionInsurancesID");

                    b.ToTable("CustomerInsurance");
                });

            modelBuilder.Entity("DataLayer.Models.InsurancesDescription.DescriptionOfBodyInsurance", b =>
                {
                    b.Property<int>("BodyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarCapacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarChassisNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarEngineNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarModel")
                        .HasColumnType("int");

                    b.Property<float>("CarPrice")
                        .HasColumnType("real");

                    b.Property<string>("CarTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConditionOfCarBodyInsurancesID")
                        .HasColumnType("int");

                    b.Property<string>("PercentageOfInsuranceDiscount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StyleCar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TowTruckCar")
                        .HasColumnType("bit");

                    b.Property<string>("TypeOfCar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsedCar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VinCar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BodyID");

                    b.ToTable("BodyInsurance");
                });

            modelBuilder.Entity("DataLayer.Models.InsurancesDescription.DescriptionOfThirdPartyInsurance", b =>
                {
                    b.Property<int>("ThirdPartyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarCapacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarChassisNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarEngineNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CarModel")
                        .HasColumnType("int");

                    b.Property<string>("CarTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverDiscountPercentage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinancialCoverageOfCarThirdPartyInsurancesID")
                        .HasColumnType("int");

                    b.Property<string>("PercentageOfInsuranceDiscount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StyleCar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TowTruckCar")
                        .HasColumnType("bit");

                    b.Property<string>("TypeOfCar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsedCar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VinCar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThirdPartyID");

                    b.ToTable("ThirdPartyInsurance");
                });

            modelBuilder.Entity("DataLayer.Models.InsurancesOfCustomer", b =>
                {
                    b.Property<int>("InsurancesForCustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescriptionInsurances")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameInsurances")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsurancesForCustomerID");

                    b.ToTable("InsurancesOfCustomer");
                });

            modelBuilder.Entity("DataLayer.Models.LoginCustomer", b =>
                {
                    b.Property<int>("NationalCodeCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PasswordCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NationalCodeCustomer");

                    b.ToTable("CustomerLogin");
                });

            modelBuilder.Entity("DataLayer.Models.RegisterCustomer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adrress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InsurancesForCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Password")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RepeatPassword")
                        .HasColumnType("int");

                    b.HasKey("CustomerID");

                    b.ToTable("CustomerRegisteration");
                });
#pragma warning restore 612, 618
        }
    }
}
